### ISSUE TITLE
RDR1 Error: Header Location Out Of Bounds

### ISSUE THREAD

**Issue by xTheDevilRazedMe** [NativeFunction/RASM#3]
Hey, i have a bug to report.
RASM works flawlessly on decompiling and recompiling the rage scripts on gta and rdr2.
But i haven't got it to work for RDR1 at all. Below are some examples

i did switch the platform to xbox and tried decompiling an xbox script,, it didnt give this error, however it did decompile the script to a empty xsa with only header location data.

I was wondering if there was something i missed or if this is an error in the tool or something.
i been wanting to check this tool out and i finally got some free time.
Like i said works like a charm for the other games but its not working for RDR

//example
C:\Users\Tyler\Desktop\RASM.v0.9.0>rasm.exe -target RDR -platform PSX -dec bin/example.csc bin/example-dec.csa -ow
Error: Header Location Out Of Bounds
//main.csc
C:\Users\Tyler\Desktop\RASM.v0.9.0>rasm.exe -target RDR -platform PSX -dec bin/main.csc bin/main.csa -ow
Error: Header Location Out Of Bounds
Press ENTER to exit...

**Comment by NativeFunction** [comment]
Send me the script and ill check it out.
