### ISSUE TITLE
Can the game accept scripts compiled by this program?

### ISSUE THREAD

**Issue by InsaneLuv** [NativeFunction/RASM#5]
Did I understand correctly, you can decompile and change for example freemode.ysс and after compilation the game will accept this file?

**Comment by NativeFunction** [comment]
This compiles a new script made in c into the proprietary bytecode from the rage engine. For the newer games the output has been less focused on loading from the file and more focused on injection.

**Comment by InsaneLuv** [comment]
> This compiles a new script made in c into the proprietary bytecode from the rage engine. For the newer games the output has been less focused on loading from the file and more focused on injection.

I tried to decompile the original script file from GTA 5 "magdemo2.ysc", but it didn't work. Apparently I did not understand the purpose of this program or am I doing something wrong?

Command:
`rasm.exe -target GTAV -platform PC -dec bin/magdemo2.ysc bin/magdemo2-dec.ysa -ow -v`

Output:
```
м<и~в 0зU▒E▄╕←пХПХ)↑в☺Ю1Bио╨╣╪d◄▌9╤▌▌,ТЁu"╨╚Ш╕$↑W╣&╕Qфs║ь╕♂ ▌Є╖єа>ХєчжIЛяу╙∙иD↑[g╚I:v↑╬►7BX│) ScriptName
2563297314 NativesCount
1978700332 GlobalsCount
3104297134 CodeLength
0 TotalStringLength
22390536 PageMapOffset
0 ScriptNameOffset
213545956 GlobalsOffset
15972338 NativesOffset
119022776 StaticsOffset
93296047 CodeBlocksOffset
263001489 StringBlocksOffset
```

My task is to change exactly the original script files. If this program is not about that - sorry for the stupidity.
Then Ild like to know if it is possible to order the creation of such a program from you especially for me? ofc paid
if it is theoretically possible

**Comment by NativeFunction** [comment]
I was under the impression that you were talking about SC-CL, my bad. If you would send me the script I'll look into it.

**Comment by InsaneLuv** [comment]
for example:
https://github.com/Primexz/GTAV-Decompiled-Scripts/raw/master/raw_scripts/freemode.ysc
https://github.com/Primexz/GTAV-Decompiled-Scripts/raw/master/raw_scripts/abigail1.ysc

When working with them, the problem is the same as with the file I mentioned

**Comment by NativeFunction** [comment]
The program does not support the RSC container. In Open IV you have to click "Save Content/Export" to get the script contents. Then you can open the .full file.

**Comment by InsaneLuv** [comment]
> The program does not support the RSC container. In Open IV you have to click "Save Content/Export" to get the script contents. Then you can open the .full file.

can i DM you somewhere?

**Comment by NativeFunction** [comment]
Sure add me on discord Native Function#8736
